CC = arm-none-linux-gnueabi-gcc



all :
	$(CC) -static -o fpga_test_led fpga_test_led.c
	$(CC) -static -o fpga_test_fnd fpga_test_fnd.c
	$(CC) -static -o fpga_test_buzzer fpga_test_buzzer.c
	$(CC) -static -o fpga_test_push_switch fpga_test_push_switch.c
	$(CC) -static -o fpga_test_dot fpga_test_dot.c
	$(CC) -static -o fpga_test_dip_switch fpga_test_dip_switch.c
	$(CC) -static -o fpga_test_step_motor fpga_test_step_motor.c
	$(CC) -static -o fpga_test_text_lcd fpga_test_text_lcd.c
	
